FROM python:3-alpine

LABEL maintainer="Morten Amundsen <me@mortenamundsen.me>"

RUN apk add --update busybox

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install -r requirements.txt

COPY . /usr/src/app

RUN cat crontab >> /etc/crontabs/root

CMD env >> /etc/environment && busybox syslogd && crond -f